[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-gatsby"

[build.environment]
  GATSBY_TELEMETRY_DISABLED = "1"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*" 