backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} \"{{slug}}\""
    update: "Update {{collection}} \"{{slug}}\""
    delete: "Delete {{collection}} \"{{slug}}\""
    uploadMedia: "Upload \"{{path}}\""
    deleteMedia: "Delete \"{{path}}\""

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/content/pages"
    create: true
    slug: "{{fields.slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"} 